service: apollo-server-lambda-test

plugins:
  - ./../../../

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs12.x
  versionFunctions: false

functions:
  graphql:
    events:
      - http:
          method: any
          path: graphql
    handler: src/index.graphql
