# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: basic

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiKeys:
    - token
# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
      - http:
          path: hello
          method: post

  rejectedPromise:
    handler: src/handler.rejectedPromise
    events:
      - http:
          path: rejectedPromise
          method: any

  helloAuthorizerWithArn:
    handler: src/handler.hello
    events:
      - http:
          path: helloAuthorizerWithArn
          method: get
          authorizer:
            arn: sometest
  helloAuthorizerWithAuthorizerId:
    handler: src/handler.hello
    events:
      - http:
          path: helloAuthorizerWithAuthorizerId
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: commonAuthorizerId

  helloAuthorizerWithFunctionName:
    handler: src/handler.hello
    events:
      - http:
          path: helloAuthorizerWithCustomFunction
          method: get
          authorizer:
            name: authFunction
            identitySource: method.request.header.Authorization #Required for serverless-offline, although it's a default
            resultTtlInSeconds: 0 #prevents caching the authorizer

  authFunction:
    handler: src/handler.authFunction

  hello500:
    handler: src/handler.hello500
    events:
      - http:
          path: hello500
          method: get
      - http:
          path: hello500
          method: post

  helloLambdaIntegration:
    handler: src/handler.helloLambdaIntegration
    events:
      - http:
          path: helloLambdaIntegration
          method: get
          integration: lambda
      - http:
          path: helloLambdaIntegration
          method: post
          integration: lambda

  helloLambdaIntegration500:
    handler: src/handler.helloLambdaIntegration500
    events:
      - http:
          path: helloLambdaIntegration500
          method: get
          integration: lambda
      - http:
          path: helloLambdaIntegration500
          method: post
          integration: lambda

  #      - s3: ${env:BUCKET}
  #      - schedule: rate(10 minutes)
  #      - sns: greeter-topic
  basicAuthentication:
    handler: src/handler.basicAuthentication
    events:
      - http:
          path: fn2
          method: GET
          private: true

  samePathPublicGet:
    handler: src/handler.hello
    events:
      - http:
          path: fn3
          method: GET

  samePathPrivatePost:
    handler: src/handler.basicAuthentication
    events:
      - http:
          path: fn3
          method: POST
          private: true

  pathParams:
    handler: src/handler.pathParams
    events:
      - http:
          path: /pathParams/{id}
          method: GET

  failure:
    handler: src/handler.failure
    events:
      - http:
          path: /failure
          method: GET

  catchAll:
    handler: src/handler.catchAll
    events:
      - http:
          path: /{proxy+}
          method: ANY

# you can add CloudFormation resource templates here
resources:
  Resources:
    EchoProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        PathPart: echo/{proxy+}
    EchoProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: EchoProxyResource
        HttpMethod: ANY
        Integration:
          IntegrationHttpMethod: ANY
          Type: HTTP_PROXY
          Uri: http://mockbin.org/request/{proxy}
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
