service: dev-http

plugins:
  - ./../../../src/main.js

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          # integration: lambda
          method: get
          path: hello
    handler: handler.hello
