service: lambda-invoke-aws-sdk-v2

configValidationMode: error
deprecationNotificationMode: error

plugins:
  - serverless-offline

provider:
  architecture: arm64
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
          Effect: Allow
          Resource: "*"
  memorySize: 1024
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          method: get
          path: test-handler
    handler: src/handler.hello

  toBeInvoked:
    handler: src/handler.toBeInvoked
