service: alb

configValidationMode: error

plugins:
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs16.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:us-east-1:12345:listener/app/my-load-balancer/50dc6c495c0c9188/50dc6c495c0c9188
          priority: 1
          conditions:
            method: GET
            path: hello
    handler: handler.hello
