name: CI

on:
  - push
  - pull_request

jobs:
  lint_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 12
          - 14
          - 16
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      # https://github.com/actions/runner/issues/241
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty npm test
