name: node.js

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  FORCE_COLOR: 1
  PRINT_OFFLINE_OUTPUT: 1
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  build:
    name: "[${{ matrix.os }}] node.js v${{ matrix.node-version }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-go@v4
        with:
          go-version: "1"

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - run: npm ci

      - run: npm run prettier

      - run: npm run lint

      - run: npm test
